# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Decoding_HMM <- function(allprobs, mGamma, T, K) {
    .Call(`_MSGARCH_Decoding_HMM`, allprobs, mGamma, T, K)
}

getDelta <- function(gamma, m) {
    .Call(`_MSGARCH_getDelta`, gamma, m)
}

Viterbi <- function(mLLK, mGamma, iK) {
    .Call(`_MSGARCH_Viterbi`, mLLK, mGamma, iK)
}

EM_HMM <- function(vY, K, maxIter = 1e3L, tol = 1e-8, constraintZero = TRUE) {
    .Call(`_MSGARCH_EM_HMM`, vY, K, maxIter, tol, constraintZero)
}

EM_MM <- function(vY, K, maxIter = 1e3L, tol = 1e-8, constraintZero = TRUE) {
    .Call(`_MSGARCH_EM_MM`, vY, K, maxIter, tol, constraintZero)
}

MapParameters_univ <- function(vTheta_tilde, Dist, bSkew) {
    .Call(`_MSGARCH_MapParameters_univ`, vTheta_tilde, Dist, bSkew)
}

UnmapParameters_univ <- function(vTheta, Dist, bSkew) {
    .Call(`_MSGARCH_UnmapParameters_univ`, vTheta, Dist, bSkew)
}

SimplexUnmapping <- function(vOmega, iK) {
    .Call(`_MSGARCH_SimplexUnmapping`, vOmega, iK)
}

SimplexMapping <- function(vPhi, iK) {
    .Call(`_MSGARCH_SimplexMapping`, vPhi, iK)
}

dUnivLike <- function(vZ, sDist, bSkew, dXi = 1.0, dNu = 7.0) {
    .Call(`_MSGARCH_dUnivLike`, vZ, sDist, bSkew, dXi, dNu)
}

